import { Document, Image, Page, Polygon, StyleSheet, Svg, Text, View } from '@react-pdf/renderer'
import type { DiscProfile, TraitKey } from '../../types/disc'
import type { BrandingConfig } from '../../theme.config'

export type ExecutivePdfLabels = {
  brand: string; reportTitle: string; executiveProfile: string; generated: string; primary: string; secondary: string; profileOverview: string; narrative: string; narrativeText: string; scores: string; behaviouralInsights: string; communication: string; workStyle: string; stressTriggers: string; growthAreas: string; conflictManagement: string; coachingRecommendations: string; conflictText: string; coachingPoints: string[]; actionPlan: string; actionPlanIntro: string; notes: string; traitNames: Record<TraitKey, string>; communicationText: string; workStyleText: string; stressText: string; growthPoints: string[]; watermark: string
}

type Props = { profile: DiscProfile | null; primaryTrait: TraitKey; secondaryTrait: TraitKey; candidateName: string; generatedAt: string; labels: ExecutivePdfLabels; branding?: BrandingConfig }

const styles = StyleSheet.create({
  page: { padding: 48, fontFamily: 'Helvetica', color: '#2f241d', backgroundColor: '#fffaf5' }, cover: { justifyContent: 'space-between' }, eyebrow: { fontSize: 10, letterSpacing: 2.2, color: '#8b7565', textTransform: 'uppercase' }, title: { fontSize: 34, fontFamily: 'Times-Bold', lineHeight: 1.2, marginTop: 14 }, subtitle: { fontSize: 14, color: '#5f4c3d', lineHeight: 1.6, marginTop: 14 }, badge: { alignSelf: 'flex-start', borderRadius: 18, paddingHorizontal: 14, paddingVertical: 8, marginTop: 22, fontSize: 12, fontFamily: 'Helvetica-Bold' }, footer: { fontSize: 8.5, color: '#8b7565', marginTop: 20 }, sectionTitle: { fontSize: 22, fontFamily: 'Times-Bold', marginBottom: 14 }, card: { borderWidth: 1, borderColor: '#e8dfd6', borderRadius: 14, padding: 14, backgroundColor: '#fffdfb', marginBottom: 12 }, cardTitle: { fontSize: 10, letterSpacing: 1.5, textTransform: 'uppercase', color: '#8b7565', marginBottom: 7 }, body: { fontSize: 11, lineHeight: 1.65, color: '#5f4c3d' }, scoreRow: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 7, borderBottomWidth: 1, borderBottomColor: '#efe3d6' }, scoreName: { fontSize: 11, fontFamily: 'Helvetica-Bold' }, scoreValue: { fontSize: 11, fontFamily: 'Helvetica-Bold' }, grid: { flexDirection: 'row', flexWrap: 'wrap', gap: 12 }, half: { width: '48.7%' }, bullet: { flexDirection: 'row', marginTop: 7 }, bulletDot: { width: 10 }, planLine: { borderBottomWidth: 1, borderBottomColor: '#d9c8b7', height: 30, marginTop: 5 }, watermark: { position: 'absolute', top: '47%', left: 0, right: 0, textAlign: 'center', fontSize: 32, color: '#8b5e3c', opacity: 0.09, fontFamily: 'Helvetica-Bold', transform: 'rotate(-32deg)' }, brandHeader: { flexDirection: 'row', alignItems: 'center', gap: 7, marginBottom: 10 }, brandLogo: { width: 24, height: 24, objectFit: 'contain' }, metricTile: { width: '31.8%', borderRadius: 12, padding: 10, backgroundColor: '#f7efe6', borderWidth: 1, borderColor: '#eadfd1' }, metricValue: { fontSize: 19, fontFamily: 'Helvetica-Bold', marginTop: 4 },
})

function Header({ branding, labels }: { branding?: BrandingConfig; labels: ExecutivePdfLabels }) {
  if (!branding?.agencyName) return <Text style={styles.eyebrow}>{labels.brand}</Text>
  return <View style={styles.brandHeader}>{branding.logoUrl ? <Image source={branding.logoUrl} style={styles.brandLogo} /> : null}<Text style={[styles.eyebrow, { color: branding.accentColor }]}>Prepared by {branding.agencyName} | Powered by {labels.brand}</Text></View>
}

function Footer({ branding, labels, candidateName, generatedAt }: Pick<Props, 'branding' | 'labels' | 'candidateName' | 'generatedAt'>) {
  return <Text style={styles.footer}>{branding?.footerNote || `${labels.brand} - ${candidateName} - ${generatedAt}`}</Text>
}

function radarPoints(scores: DiscProfile['scores']) {
  const ordered = ['D', 'I', 'S', 'C'] as TraitKey[]
  return ordered.map((trait, index) => { const value = scores.find((score) => score.trait === trait)?.percentage ?? 0; const angle = (Math.PI * 2 * index) / 4 - Math.PI / 2; return `${100 + Math.cos(angle) * (value * 0.65)},${100 + Math.sin(angle) * (value * 0.65)}` }).join(' ')
}

export default function ExecutivePdfReport({ profile, primaryTrait, secondaryTrait, candidateName, generatedAt, labels, branding }: Props) {
  const scores = profile?.scores ?? []
  const accent = branding?.accentColor ?? '#8b5e3c'
  const typeface = branding?.typography === 'modern' ? 'Helvetica' : 'Times-Roman'
  const titleTypeface = branding?.typography === 'modern' ? 'Helvetica-Bold' : 'Times-Bold'
  const watermark = branding ? null : <Text fixed style={styles.watermark}>{labels.watermark}</Text>
  const header = <Header branding={branding} labels={labels} />
  const footer = <Footer branding={branding} labels={labels} candidateName={candidateName} generatedAt={generatedAt} />
  return <Document title={`${labels.brand} - ${candidateName}`} author={labels.brand}>
    <Page size="A4" style={[styles.page, styles.cover, { fontFamily: typeface }]}>{watermark}{header}<View><Text style={[styles.eyebrow, { color: accent }]}>{labels.brand}</Text><Text style={[styles.title, { color: accent, fontFamily: titleTypeface }]}>{labels.reportTitle}</Text><Text style={styles.subtitle}>{labels.executiveProfile}</Text><Text style={[styles.badge, { backgroundColor: `${accent}22` }]}>{labels.traitNames[primaryTrait]} / {labels.traitNames[secondaryTrait]}</Text></View><View><Text style={[styles.title, { fontFamily: titleTypeface }]}>{candidateName}</Text><Text style={styles.subtitle}>{labels.generated}: {generatedAt}</Text>{footer}</View></Page>
    <Page size="A4" style={styles.page}>{watermark}{header}<Text style={[styles.sectionTitle, { color: accent }]}>{labels.profileOverview}</Text><View style={styles.grid}>{[[labels.primary, labels.traitNames[primaryTrait]], [labels.secondary, labels.traitNames[secondaryTrait]], ['Profile strength', `${scores.find((score) => score.trait === primaryTrait)?.percentage ?? 0}%`]].map(([label, value]) => <View key={label} style={styles.metricTile}><Text style={styles.cardTitle}>{label}</Text><Text style={[styles.metricValue, { color: accent }]}>{value}</Text></View>)}</View><View style={[styles.card, { alignItems: 'center', marginTop: 12 }]}><Svg width="240" height="220" viewBox="0 0 200 200"><Polygon points="100,20 180,100 100,180 20,100" fill="none" stroke="#dcc9b7" strokeWidth="1" /><Polygon points="100,52 148,100 100,148 52,100" fill="none" stroke="#dcc9b7" strokeWidth="1" /><Polygon points={radarPoints(scores)} fill={accent} fillOpacity="0.35" stroke={accent} strokeWidth="2" /></Svg></View><View style={styles.card}><Text style={styles.cardTitle}>{labels.scores}</Text>{scores.map((score) => <View key={score.trait} style={styles.scoreRow}><Text style={styles.scoreName}>{labels.traitNames[score.trait]}</Text><Text style={[styles.scoreValue, { color: accent }]}>{score.percentage}%</Text></View>)}</View><View style={styles.card}><Text style={styles.cardTitle}>{labels.narrative}</Text><Text style={styles.body}>{labels.narrativeText}</Text></View>{footer}</Page>
    <Page size="A4" style={styles.page}>{watermark}{header}<Text style={[styles.sectionTitle, { color: accent }]}>{labels.behaviouralInsights}</Text><View style={styles.grid}>{[[labels.communication, labels.communicationText], [labels.workStyle, labels.workStyleText], [labels.stressTriggers, labels.stressText]].map(([title, body]) => <View key={title} style={[styles.card, styles.half]}><Text style={styles.cardTitle}>{title}</Text><Text style={styles.body}>{body}</Text></View>)}<View style={[styles.card, styles.half]}><Text style={styles.cardTitle}>{labels.growthAreas}</Text>{labels.growthPoints.map((point) => <View key={point} style={styles.bullet}><Text style={[styles.bulletDot, { color: accent }]}>-</Text><Text style={styles.body}>{point}</Text></View>)}</View></View>{footer}</Page>
    <Page size="A4" style={styles.page}>{watermark}{header}<Text style={[styles.sectionTitle, { color: accent }]}>Deep leadership insights</Text><View style={styles.grid}>{[['Leadership Style', labels.communicationText], ['Ideal Work Environment', labels.workStyleText], ['Motivators & Triggers', labels.stressText], ['Actionable Growth Areas', labels.growthPoints.join(' ') ]].map(([title, body]) => <View key={title} style={[styles.card, styles.half]}><Text style={styles.cardTitle}>{title}</Text><Text style={styles.body}>{body}</Text></View>)}</View>{footer}</Page>
    <Page size="A4" style={styles.page}>{watermark}{header}<Text style={[styles.sectionTitle, { color: accent }]}>{labels.conflictManagement}</Text><View style={styles.card}><Text style={styles.cardTitle}>{labels.conflictManagement}</Text><Text style={styles.body}>{labels.conflictText}</Text></View><View style={styles.card}><Text style={styles.cardTitle}>{labels.coachingRecommendations}</Text>{labels.coachingPoints.map((point) => <View key={point} style={styles.bullet}><Text style={[styles.bulletDot, { color: accent }]}>-</Text><Text style={styles.body}>{point}</Text></View>)}</View>{footer}</Page>
    <Page size="A4" style={styles.page}>{watermark}{header}<Text style={[styles.sectionTitle, { color: accent }]}>{labels.actionPlan}</Text><Text style={styles.body}>{labels.actionPlanIntro}</Text>{[1, 2, 3].map((item) => <View key={item} style={[styles.card, { marginTop: 18 }]}><Text style={styles.cardTitle}>{item}. {labels.notes}</Text><View style={styles.planLine} /><View style={styles.planLine} /><View style={styles.planLine} /></View>)}{footer}</Page>
  </Document>
}
