import { motion } from 'framer-motion'

type Props = { open: boolean; onClose: () => void; onCheckout: () => void; isStartingCheckout: boolean; error: string | null }

export default function EnterprisePaywallModal({ open, onClose, onCheckout, isStartingCheckout, error }: Props) {
  if (!open) return null
  return <div className="print-hide fixed inset-0 z-[60] flex items-center justify-center bg-stone-950/60 p-4 backdrop-blur-sm" role="dialog" aria-modal="true" aria-labelledby="enterprise-paywall-title">
    <motion.div initial={{ opacity: 0, y: 18, scale: .98 }} animate={{ opacity: 1, y: 0, scale: 1 }} className="w-full max-w-lg rounded-[2rem] border border-stone-200 bg-[linear-gradient(135deg,_#fffaf5,_#f1e2d3)] p-6 shadow-2xl"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-[.24em] text-[#8b5e3c]">Enterprise / Coach</p><h2 id="enterprise-paywall-title" className="mt-2 text-2xl font-semibold text-stone-900">White-label your Executive reports</h2></div><button type="button" onClick={onClose} className="rounded-full border border-stone-300 bg-white px-3 py-1 text-sm text-stone-600">Close</button></div><p className="mt-3 text-sm leading-7 text-stone-700">Bring your own brand to client-ready DISC reports while retaining the Northstar DISC attribution.</p><ul className="mt-4 space-y-2 text-sm leading-6 text-stone-700"><li>✓ Agency name, accent colour and logo</li><li>✓ Custom report footer note</li><li>✓ Watermark-free Executive PDF exports</li></ul>{error ? <p className="mt-4 text-sm text-red-700">{error}</p> : null}<button type="button" onClick={onCheckout} disabled={isStartingCheckout} className="mt-6 inline-flex w-full items-center justify-center rounded-full bg-stone-900 px-5 py-3 text-sm font-semibold text-white disabled:opacity-60">{isStartingCheckout ? 'Opening secure checkout…' : 'Upgrade to Enterprise White-Label'}</button><p className="mt-3 text-center text-xs text-stone-500">Secure subscription checkout powered by Stripe.</p></motion.div>
  </div>
}
